### ISSUE TITLE
Flair breaks in learnR after first decorated code chunk 

### ISSUE THREAD

**Issue by dcossyleon** [r-for-educators/flair#24]
Howdy! I love this package, and I'm interesting in using it with LearnR. Decorating a chunk works well with the first instance, but not subsequent decorated chunks:

For example, the code below...

````
---
title: "Flair Test in LearnR"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(flair)
library(dplyr)

knitr::opts_chunk$set(echo = FALSE)
```


## Topic 1

### Exercise 

Here's the first flair example. It works fine.

```{r how_to_pipe, include = FALSE}
iris %>%
  group_by(Species) %>%
  summarize(mean(Sepal.Length))
```

```{r, echo = FALSE}
decorate("how_to_pipe") %>% 
  flair("%>%")
```

But the subsequent flair examples do not work in LearnR. 

```{r how_to_pipe2, echo = FALSE}
decorate('

iris %>%
  group_by(Species) %>%
  summarize(mean(Sepal.Length))

') %>%
  flair("%>%")
```
````

...renders as: 

![image](https://user-images.githubusercontent.com/29008894/93028241-76a18e00-f5e0-11ea-89f9-892e9709efad.png)

Any ideas for what might be going wrong?

**Comment by gadenbuie** [comment]
Hi @dcossyleon, I have a little insight about what's going on here and the good news is that it's not `learnr` specific!

The first example uses a named chunk and applies the flair to that chunk. Under the hood, `decorate_chunk()` is used to apply the highlighting and that function automatically sets `echo = TRUE`, resulting in the first output.

````markdown
```{r how_to_pipe, include = FALSE}
# not printed because echo=FALSE globally
iris %>%
  group_by(Species) %>%
  summarize(mean(Sepal.Length))
```

```{r, echo = FALSE}
# The code that adds the flair isn't printed because echo=FALSE
# ...but decorate() calls decorate_chunk() which overrides echo=TRUE for the output
# (because you probably wanted the flaired code to end up the doc)
decorate("how_to_pipe") %>% 
  flair("%>%")
```
````

If you add `echo = FALSE` to `decorate("how_to_pipe", echo = FALSE)`, the output goes away.

The second `decorate()` expression, on the other hand, flairs code and not a code chunk, so under the hood `decorate_code()` is called. This function _doesn't_ set `echo = TRUE` for the output.

If you add `echo = TRUE` to that `decorate()` function, the flaired code will show up in the output as expected.

````markdown
```{r how_to_pipe2, echo = FALSE}
decorate('

iris %>%
  group_by(Species) %>%
  summarize(mean(Sepal.Length))

', echo = TRUE) %>%
  flair("%>%")
```
````

![image](https://user-images.githubusercontent.com/5420529/93248772-526bbb80-f75e-11ea-8fa1-6b0160acc6c2.png)

**Comment by kbodwin** [comment]
@gadenbuie I am running out of unique words in the English language to describe your awesomeness.

Ideally `decorate_code` would default to `echo = TRUE`, adding this to the to-do list...

**Comment by gadenbuie** [comment]
I'm just happy to help! And that learnr and flair work so well together!

**Comment by dcossyleon** [comment]
Thank you!

I had missed the fact that knitr code chunk options could be set from within the `decorate()` function -- so that is really great to know and opens up many more possibilities for how I can use flair 🤩
